### ISSUE TITLE
[TASK] Programmatic Contract Deployment in Rust

### ISSUE THREAD

**Issue by Tjemmmic** [webb-tools/eigensdk-rs#6]
## Programmatic Contract Deployment in Rust

The EigenSDK-RS should include an easy way of deploying contracts to an Anvil testnet from rust. Specifically, this should be done already for the AVSs that we have, with these functions and tests ready to go out-of-the-box.

### Task Checklist
- [x] Testnet Deployment from scratch for incredible-squaring-avs
- [x] Testnet Deployment from scratch for tangle-avs
- [x] Utility functions for easily running deployments
- [x] State saving and loading functions
- [x] Contract Deployment Tests
