### ISSUE TITLE
[TASK] Github Workflow and Actions

### ISSUE THREAD

**Issue by Tjemmmic** [webb-tools/eigensdk-rs#7]
## Github Workflow and Actions

We want to have Actions automate as much as possible, in addition to the standard workflow that checks function, quality, and cleanliness.

### Task Checklist
- [x] Forge - Build contracts before running Clippy or Tests
- [x] General Workflow i.e,, Clippy, Tests, etc.
- [x] Scripts for Contract management
