### ISSUE TITLE
[CHECKLIST] Eigenlayer Rust Integration

### ISSUE THREAD

**Issue by Tjemmmic** [webb-tools/eigensdk-rs#9]
# Summary

**_NOTE: This Checklist was moved from its previous home in Gadget, some of these tasks were completed prior to the move._**

Our goal is to enable interoperability between Eigenlayer and Tangle/Gadget. We want the Incredible Squaring AVS rewritten in Rust so that it may run in a Gadget and an AVS that internally runs our Gadget or a Tangle Validator. With both of these, we are able to run Gadget/Tangle processes within an Eigenlayer AVS and Eigenlayer's AVS within our Gadget.

---

## Testing via [Local Testnet](https://docs.eigenlayer.xyz/eigenlayer/avs-guides/how-to-build-an-avs#step-2-idea-to-code-testing-and-deploying-your-avs-locally)

- [x] [TASK] AVSs Meet Contract and Operator Requirements
- [x] [TASK] Tangle AVS - Deployment on Local Testnet
- [x] #10

## [eigen-utils](https://github.com/webb-tools/gadget/tree/drew/eigen/eigen-utils) and [eigen-contracts](https://github.com/webb-tools/gadget/tree/drew/eigen/eigen-contracts)

- [x] [TASK] EigenSDK Rust Port | Utils
- [x] [TASK] Contracts
- [x] #11
- [x] #6 

## Miscellaneous
- [x] #7 
- [x] #2 
- [x] #18

### Relevant Resources/Links
https://docs.eigenlayer.xyz/eigenlayer/avs-guides/how-to-build-an-avs

**Comment by shekohex** [comment]
@Tjemmmic is this checklist done? beside from testing on testnet?
